server:
  port: 0

spring:
  application:
    name: iiiiii-accountbook

  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/accbookdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:${DB_PORT:3306}/accbookdb
    username: iiiiii
    password: iiiiii

  # jpa
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true  # change to pretty SQL text

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka